2024-12-19 10:52:13,246 [INFO] 使用 cuda 进行推理
2024-12-19 10:52:13,249 [INFO] 开始执行主程序
2024-12-19 10:52:13,250 [INFO] 开始处理视频合成任务
2024-12-19 10:52:13,250 [ERROR] 程序执行过程中出现错误: --face argument must be a valid path to video/image file
Traceback (most recent call last):
  File "inference.py", line 480, in <module>
    main()
  File "inference.py", line 342, in main
    raise ValueError('--face argument must be a valid path to video/image file')
ValueError: --face argument must be a valid path to video/image file
